name=ESP32WiFiPortal
version=1.1.0
author=Tran Nguyen Hien
maintainer= Tran Nguyen Hien
sentence=ESP32-only Wi-Fi captive portal and credential manager.
paragraph=Wi-Fi provisioning library for ESP32 Arduino Core with AP mode, captive portal, network scan, NVS credential storage, blocking and non-blocking operation.
category=Communication
url=https://github.com/NguyenHien-8/ESP32WiFiPortal
architectures=esp32
includes=ESP32WiFiPortal.h
license=Apache License V2.0
